name: Stylua
on:
  - push
  - pull_request
jobs:
  stylua:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: StyLua
        uses: JohnnyMorganz/stylua-action@76fd70c03e6340ceaf673366712db9b20560b402 # v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.20.0
          args: --check .
